services:
  app:
    entrypoint:
    - sleep
    - infinity
    image: rust-dev-env:debian
    init: true
    volumes:
    - type: bind
      source: /var/run/docker.sock
      target: /var/run/docker.sock

